using Content.Client.UserInterface.Controls;
using Content.Shared._Changed14.ResearchEvac;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Message;
using Robust.Shared.Timing;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Shared.Research;

namespace Content.Client._Changed14.ResearchEvac;

[GenerateTypedNameReferences]
public sealed partial class ResearchEvacWindow : FancyWindow
{
    public event Action? OnCallEvacButtonPressed;

    public ResearchEvacWindow()
    {
        RobustXamlLoader.Load(this);

        CallEvacButton.OnPressed += _ => OnCallEvacButtonPressed?.Invoke();
    }

    // public void SetEntity(EntityUid uid)
    // {
    //     EntityView.SetEntity(uid);
    // }
    public void Update(ResearchEvacConsoleBoundUserInterfaceState state)
    {
        CallEvacButton.Disabled = !state.CanCall;
        // Description.Text = Loc.GetString("idi-naxuy");
    }

    public void UpdateState(ResearchEvacConsoleBoundUserInterfaceState state)
    {

    }
}
