using Content.Client.UserInterface.Controls;
using Content.Shared._Changed14.ResearchEvac;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Message;
using Robust.Shared.Timing;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;
using Content.Shared.Research;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Content.Client._Changed14.ResearchEvac;

namespace Content.Client._Changed14.ResearchEvac;

[GenerateTypedNameReferences]
public sealed partial class ResearchEvacWindow : FancyWindow
{
    public event Action? OnCallEvacButtonPressed;

    public ResearchEvacWindow()
    {
        RobustXamlLoader.Load(this);

        CallEvacButton.OnPressed += _ => OnCallEvacButtonPressed?.Invoke();
    }
    public void Update(ResearchEvacConsoleBoundUserInterfaceState state)
    {
        CallEvacButton.Disabled = state.CanCall;
    }

}
